### ISSUE TITLE
Creating MetadataFile should require MetadataEditor role on collection in policy scope?

### ISSUE THREAD

**Issue by dchandekstark** [duke-libraries/dul-hydra#1505]
/cc @coblej @jt112

**Comment by coblej** [comment]
@dchandekstark For METS folder processing, we recently added an "ingest_metadata" permission (which is just an alias for "update").  I suggest that we handle MetadataFile the same way, since it is represents similar capability -- the ability to batch update metadata for items in the collection.  This approach would also be a welcome simplification since MetadataFile processing capability currently depends on being a member of a "metadata data file creators" group ( https://github.com/duke-libraries/dul-hydra/blob/develop/lib/dul_hydra/ability_definitions/metadata_file_ability_definitions.rb ).  Switching MetadataFile processing to the same permission as METS Folder processing would eliminate the need for this (Grouper) group and for the custom MetadataFile ability definition.

**Comment by dchandekstark** [comment]
+1 Sounds good to me.
